# Generated by Django 3.2.8 on 2021-10-17 03:53

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finfreedom_api', '0002_alter_profiles_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
