# Generated by Django 3.2.8 on 2021-10-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finfreedom_api', '0003_auto_20211017_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
