# Generated by Django 3.2.8 on 2021-10-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finfreedom_frontend', '0002_alter_profiles_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='account_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='credit_on_card',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='expiration_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='payment_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='security_code',
            field=models.IntegerField(blank=True),
        ),
    ]
