# Generated by Django 3.2.8 on 2021-10-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finfreedom_frontend', '0003_auto_20211017_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='security_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
